bf16: true
cutoff_len: 2048
dataset: grammar_docu
dataset_dir: data
ddp_timeout: 180000000
do_train: true
enable_liger_kernel: true
enable_thinking: true
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 8
include_num_input_tokens_seen: true
learning_rate: 5.0e-05
logging_steps: 10
lora_alpha: 32
lora_dropout: 0
lora_rank: 32
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: LLM-Research/Meta-Llama-3.1-8B-Instruct
num_train_epochs: 3.0
optim: adamw_torch
output_dir: saves/Llama-3.1-8B-Instruct/lora/CPT_train_2025-08-05-16-51-40
packing: true
per_device_train_batch_size: 2
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 50
stage: pt
template: llama3
trust_remote_code: true
warmup_steps: 500
