model_name_or_path: LLM-Research/Meta-Llama-3.1-8B-Instruct
tokenizer_name_or_path: config/ast_tokenizer_llama3_1
output_dir: saves/Llama-3.1-8B-Instruct/lora/Parallel_SFT_train_ast
do_train: true
stage: sft
template: llama3
bf16: true
cutoff_len: 4096
dataset: parallel_2k_ast
dataset_dir: data
ddp_timeout: 180000000
enable_liger_kernel: true
enable_thinking: false
finetuning_type: lora
flash_attn: auto
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
include_num_input_tokens_seen: true
num_train_epochs: 6
learning_rate: 4.0e-05
lora_alpha: 64
lora_dropout: 0
lora_rank: 64
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
logging_steps: 10
save_steps: 30
warmup_steps: 50
optim: adamw_torch
packing: false
preprocessing_num_workers: 16
plot_loss: true
report_to: none
trust_remote_code: true

